import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import QueryProvider from "@/providers/query-provider";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";
import { Sora } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";
import "./globals.css";
import { Suspense } from "react";

const sora = Sora({
  variable: "--font-Sora",
});

export const metadata: Metadata = {
  title: "Veeniu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sora.className} flex min-h-screen flex-col antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
        ></ThemeProvider>
        <SessionProvider>
          <QueryProvider>
            <NuqsAdapter>
              <Suspense>
                <Navbar />
                <main className="flex-1">{children}</main>
                <Footer />
              </Suspense>
            </NuqsAdapter>
          </QueryProvider>
        </SessionProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
